### PR TITLE
Add 'heatmap' colors to icon

### PR DESCRIPTION
**Pull request by matyasfodor**
I really badly needed this extension, but I thought I'll spice it up with some color coding: The less tabs you have open, the calmer the color is:
screen shot 2018-03-02 at 12 39 07
screen shot 2018-03-02 at 12 28 52
The maximum is reached at 40 tabs.

The code is not very clean, and it gives your extension a totally new look.
I had to redesign it since I wasn't able to change the font color in the badge, so I ended up changing the whole icon. I think it looks nice. My question is: would you like to pull my changes or should I publish it separately?

### CODE REVIEW

**Comment by allanlaal** [comment]
is this feature opt-in? 'cause it should be :)

**Comment by matyasfodor** [comment]
Afaik there's no settings page for this extension. I guess that's the only way to make it opt-in (either on the background page or in the pop-up menu. Which one would you prefer?

**Comment by allanlaal** [comment]
I personally prefer not to use this feature at all, since there is no "right" amount of tabs one can have :)

**Comment by matyasfodor** [comment]
Alright, I'll publish my fork separately then, let's see if anyone else likes it.

**Comment by asafh** [comment]
Hi @matyasfodor, of course you're free to publish your own fork. If you'd like, in the next weeks I could come up with time to add a settings page.  
Such a page could set a number range for the color gradient. Alternatively, we could just record the highest number of tabs for that user, and decay the peak if it was an anomaly. (Though the settings page could support both).

Cheers.

**Comment by matyasfodor** [comment]
Hi @asafh, I think what I came up with eventually (the code is not pushed yet) is a really different product and there's no harm in having these next to each other in play store.

**Pull request closed without merging**
